version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_nodejs
    restart: always
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
    depends_on:
      - rabbitmq
      - postgres

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
